; Replaces the default text strings for the four buttons (< Back, Next >, Cancel and Close)
MiscButtonText "Précédent" "Suivant" "Refuser" "Exécuter"

; Replaces the default text ("Completed") that is printed at the end of the install process
;CompletedText "Die SIARDexcerpt Installation wird überprüft"

; Replaces the default details button text of "Show details"
;DetailsButtonText "Details zeigen"

;!define SIP_MISSING       "n'est-ce pas un répertoire / fichier SIP valide"
!define INIT_OK           "Initialisation fait. A partir de maintenant il est possible de rechercher et d'extraire."
!define SEARCH_OK         "Recherche effectuée, ouvrir le résultat de la recherche?"
!define EXCERPT_OK        "Extraction effectuée, ouvrir l'extrait?"
!define INIT_FALSE        "Problèmes d'initialisation. Décompresser manuellement et redémarrer s'il vous plaît."
!define SEARCH_FALSE      "Recherche effectuée, aucun résultat de recherche."
!define EXCERPT_FALSE     "Problèmes d'extraction, ouvrir le fichier log?"
!define PROG_ERR          "Erreur Java lorsque l'exécution du programme:"
!define LOG_ERR           "Pas d'autorisation d'écriture pour le répertoire de logging:"

!define NextButtonText    "&Exécuter"

;----------------------
!define WILDCARD                  "Field 1"
!define HELP_Button               "Field 2"
!define 1INIT_RadioButton         "Field 3"
!define 2SEARCH_RadioButton       "Field 4"
!define 3EXCERPT_RadioButton      "Field 5"
!define SIARD_Lable               "Field 6"
;!define INPUT_FolderRequest       "Field 7"
!define SIARD_FileRequest         "Field 8"
!define SIARD_FileSelect          "Field 9"
;!define START_Button              "Field 10"
;!define EDIT_Konfiguration        "Field 11"
;!define MAINTABLE_Lable           "Field 12"
!define JVM_Droplist              "Field 13"
!define JVM_Value                 "Field 14"
!define CONFIG_Lable              "Field 16"
!define CONFIG_FileRequest        "Field 18"
!define CONFIG_FileSelect         "Field 19"
!define SEARCHEXCERPT_Lable       "Field 26"
!define SEARCHEXCERPT_Text        "Field 29"

;----------------------
!define WILDCARDTXT              "En tant que wildcard le * (astérisque) est utilisé"
!define HELP_ButtonTXT           "&Aide"
!define 1INIT_TextTXT            "Initialisation"
!define 2SEARCH_TextTXT          "Recherche"
!define 3EXCERPT_TextTXT         "Extraction"
!define START_TextTXT            "Exécuter:"
!define 1INIT_RadioButtonTXT     "1. ${1INIT_TextTXT}"
!define 2SEARCH_RadioButtonTXT   "2. ${2SEARCH_TextTXT}"
!define 3EXCERPT_RadioButtonTXT  "3. ${3EXCERPT_TextTXT}"
!define SIARD_LableTXT           "Fichier SIARD:"
;!define INPUT_FolderRequestTXT   "Choisir un dossier ..."
!define SIARD_FileRequestTXT     "Fichier..."
!define SIARD_FileSelectTXT      "Fichier SIARD ou chemin"
;!define START_ButtonTXT          "${START_TextTXT} ${1INIT_TextTXT}"
;!define EDIT_KonfigurationTXT    "Modifier la configuration ..."
;!define MAINTABLE_LableTXT       "-> "
!define JVM_DroplistTXT          "Option de JVM:"
!define CONFIG_LableTXT          "Configuration:"
!define CONFIG_FileRequestTXT    "Fichier..."
!define CONFIG_FileSelectTXT     "Fichier de configuration / (..) / maintable"
!define SEARCHEXCERPT_LableTXT   "${2SEARCH_TextTXT}:"
!define SEARCHEXCERPT_TextTXT    "${2SEARCH_TextTXT} / ${3EXCERPT_TextTXT} de"

;----------------------
;!define FOLDER_SelectTXT         "S'il vous plaît choisissez un dossier valide"
!define FILE_SelectTXT           "S'il vous plaît choisissez un fichier valide"
