; Replaces the default text strings for the four buttons (< Back, Next >, Cancel and Close)
MiscButtonText "Previous" "Next" "Reject" "Run"

; Replaces the default text ("Completed") that is printed at the end of the install process
CompletedText "The SIARDexcerpt installation is beeing checked"

; Replaces the default details button text of"Show details"
DetailsButtonText "Show Details"

;!define SIP_MISSING          "Is not a valid file SIP / SIP directory"
!define INIT_OK     	      "Initialization done. From now on can be searched and extracted."
!define SEARCH_OK       	  "Search performed; open search result?"
!define EXCERPT_OK      	  "Extraction performed; open extract?"
!define INIT_FALSE      	  "Initialization problems. Please unpack and restart manually. "
!define SEARCH_FALSE    	  "Search performed, no search results."
!define EXCERPT_FALSE   	  "Excerpt problems, open log file?"
!define PROG_ERR              "General Java runtime error:"
!define LOG_ERR               "No write access in LOG folder:"

!define NextButtonText        "&Run"

;----------------------
!define WILDCARD                  "Field 1"
!define HELP_Button               "Field 2"
!define 1INIT_RadioButton         "Field 3"
!define 2SEARCH_RadioButton       "Field 4"
!define 3EXCERPT_RadioButton      "Field 5"
!define SIARD_Lable               "Field 6"
;!define INPUT_FolderRequest       "Field 7"
!define SIARD_FileRequest         "Field 8"
!define SIARD_FileSelect          "Field 9"
;!define START_Button              "Field 10"
;!define EDIT_Konfiguration        "Field 11"
;!define MAINTABLE_Lable           "Field 12"
!define JVM_Droplist              "Field 13"
!define JVM_Value                 "Field 14"
!define CONFIG_Lable              "Field 16"
!define CONFIG_FileRequest        "Field 18"
!define CONFIG_FileSelect         "Field 19"
!define SEARCHEXCERPT_Lable       "Field 26"
!define SEARCHEXCERPT_Text        "Field 29"

; ----------------------
!define WILDCARDTXT              "Use * (asterisk) as wildcard"
!define HELP_ButtonTXT           "&Help"
!define 1INIT_TextTXT            "Initialization"
!define 2SEARCH_TextTXT          "Search"
!define 3EXCERPT_TextTXT         "Excerption"
;!define START_TextTXT            "Run:"
!define 1INIT_RadioButtonTXT     "1. ${1INIT_TextTXT}"
!define 2SEARCH_RadioButtonTXT   "2. ${2SEARCH_TextTXT}"
!define 3EXCERPT_RadioButtonTXT  "3. ${3EXCERPT_TextTXT}"
!define SIARD_LableTXT           "SIARD-file:"
;!define INPUT_FolderRequestTXT   "Ordner auswählen ..."
!define SIARD_FileRequestTXT     "File..."
!define SIARD_FileSelectTXT      "SIARD-file or path"
;!define START_ButtonTXT          "${START_TextTXT} ${1INIT_TextTXT}"
;!define EDIT_KonfigurationTXT    "Edit Configuration ..."
;!define MAINTABLE_LableTXT       "-> "
!define JVM_DroplistTXT          "JVM option:"
!define CONFIG_LableTXT          "Configuration:"
!define CONFIG_FileRequestTXT    "File..."
!define CONFIG_FileSelectTXT     "configuration file / (..) / maintable"
!define SEARCHEXCERPT_LableTXT   "${2SEARCH_TextTXT}:"
!define SEARCHEXCERPT_TextTXT    "${2SEARCH_TextTXT} / ${3EXCERPT_TextTXT} of"

; ----------------------
;!define FOLDER_SelectTXT        "Please choose a valid folder"
!define FILE_SelectTXT          "Please choose a valid file "
