/* This file contains dynamically generated data - all edits will be lost during report generation!
*/

var cals_dict =  
{
    "ReportGeneratedBy": "Report generated by",
    "SummaryReportFor": "Summary report for",
    "Profile": "Profile",
    "ProcessPages": "Processed pages",
    "ProcessedBy": "Processed by",
    "ProcessedByOn": "on",
    "Fixups": "Fixups",
    "Errors": "Errors",
    "Warnings": "Warnings",
    "Infos": "Infos",
    "DocumentInfo": "Document information",
    "FileName": "File name",
    "Path": "Path",
    "PDFVersionNumber": "PDF Version",
    "FileSizeGB": "File size (GB)",
    "FileSizeMB": "File size (MB)",
    "FileSizeKB": "File size (kB)",
    "FileSizeByte": "File size (Byte)",
    "Title": "Title",
    "Creator": "Creator",
    "Producer": "Producer",
    "Created": "Created",
    "Modified": "Modified",
    "Trapping": "Trapping",
    "Standards": "Standards",
    "NumberOfPlates": "Number of plates",
    "NamesOfPlates": "Names of plates",
    "Environment": "Environment",
    "OperatingSystem": "Operating system"
}
;
var cals_env_info =  
{
    "date": "2013-09-17T10:00:00+02:00",
    "tool_name": "pdfToolbox",
    "tool_variant": "Server",
    "tool_version": "7.0 (250)",
    "user_name": "callas software - support team",
    "machine_name": "callas software - Test environment MacOS 10.8",
    "os_version_text": "Mac OS X 10.8.4",
    "os_version_major": "10",
    "os_version_minor": "8"
}
;
var cals_doc_info =  
{
    "docs":
    [
        {
            "file_name": "Advertisement_callas_v2_final_210x282.pdf",
            "file_path": "\/Volumes\/Work\/Reports\/Testfiles\/5",
            "pdf_version": "1.4",
            "file_size": "1234455",
            "docinfo":
            {
                "Title": "",
                "Creator": "Adobe InDesign CS5 (7.0.4)",
                "Producer": "Adobe PDF Library 9.9",
                "CreationDate": "D:20120125165553+01'00'",
                "ModDate": "D:20130909172756+02'00'",
                "Trapped": "False"
            },
            "plates":
            [
                "Cyan",
                "Magenta",
                "Yellow",
                "Black"
            ],
            "nplates": "4",
            "standards": "",
            "num_pages": "2",
            "pages":
            [
                {
                    "page": "1",
                    "page_label": "1",
                    "page_img": "img\/cals_pages\/20\/1\/cals_src_a.png"
                }
            ]
        }
    ]
}
;
var cals_res_info =  
{
    "profile_name": "Prepress Processplan v7.0 (incl. Imposition)",
    "profile_type": "Profile",
    "processed_pages": "2",
    "errors": "34",
    "warnings": "26",
    "infos": "11",
    "steps":
    [
        {
            "type": "action",
            "name": "Booklet (without cut marks)"
        },
        {
            "type": "fixup",
            "name": "Convert color to B\/W",
            "errors": "0",
            "warnings": "0",
            "infos": "0",
            "hits": "",
            "fixups":
            [
                {
                    "fixup_name": "Set transparency blend color space",
                    "succeeded": "18",
                    "failed": "0"
                },
                {
                    "fixup_name": "Convert color to B\/W",
                    "succeeded": "71",
                    "failed": "0"
                }
            ]
        },
        {
            "type": "rule",
            "name": "Color images",
            "errors": "0",
            "warnings": "0",
            "infos": "0",
            "hits": "",
            "fixups": ""
        },
        {
            "type": "profile",
            "name": "Prepress profile v7.0",
            "errors": "34",
            "warnings": "26",
            "infos": "11",
            "hits":
            [
                {
                    "rule_name": "Text objects",
                    "severity": "warning",
                    "pages": "1",
                    "matches": "26"
                },
                {
                    "rule_name": "Resolution of color and grayscale images is greater than 250 ppi",
                    "severity": "info",
                    "pages": "1",
                    "matches": "9"
                },
                {
                    "rule_name": "Vector objects (filled)",
                    "severity": "error",
                    "pages": "1",
                    "matches": "34"
                },
                {
                    "rule_name": "Vector objects (stroked)",
                    "severity": "info",
                    "pages": "1",
                    "matches": "2"
                }
            ],
            "fixups":
            [
                {
                    "fixup_name": "Set transparency blend color space",
                    "succeeded": "18",
                    "failed": "0"
                },
                {
                    "fixup_name": "Convert color to sRGB",
                    "succeeded": "71",
                    "failed": "0"
                },
                {
                    "fixup_name": "Flip pages vertically",
                    "succeeded": "2",
                    "failed": "0"
                }
            ]
        }
    ]
}
;
