/* This file contains dynamically generated data - all edits will be lost during report generation!
*/

var cals_dict =  
{
	"AllPagesSame" : "All pages have the same size",
	"AlternateColorSpace" : "Alternate color space",
	"AlternateColorValue" : "Alternate color value",
	"Created" : "Created",
	"Creator" : "Creator",
	"DefinedSize" : "Defined size",
	"DocumentInfo" : "Document information",
	"EffectiveSize" : "Effective size",
	"Environment" : "Environment",
	"Errors" : "Errors",
	"FileName" : "File name",
	"FileSizeByte" : "File size (Byte)",
	"FileSizeGB" : "File size (GB)",
	"FileSizeKB" : "File size (kB)",
	"FileSizeMB" : "File size (MB)",
	"FixupMatch" : 
	{
		"FixupCount" : "",
		"FixupName" : "",
		"msg" : "@(FixupName) (@(FixupCount) change)"
	},
	"FixupMatches" : 
	{
		"FixupCount" : "",
		"FixupName" : "",
		"msg" : "@(FixupName) (@(FixupCount) changes)"
	},
	"Fixups" : "Fixups",
	"Infos" : "Infos",
	"InkAmount" : "Ink amount",
	"InkCoverage" : "Ink coverage",
	"LastResult" : "Last result",
	"MatchValue" : 
	{
		"MATCH_COUNT" : "",
		"msg" : "(@(MATCH_COUNT) match)"
	},
	"MatchesValue" : 
	{
		"MATCH_COUNT" : "",
		"msg" : "(@(MATCH_COUNT) matches)"
	},
	"Modified" : "Modified",
	"NamesOfPlates" : "Names of plates",
	"NoProblemsFound" : "No problems found",
	"NoSpotColors" : "No spot color in this document",
	"NumberOfPlates" : "Number of plates",
	"OperatingSystem" : "Operating system",
	"PDFVersionNumber" : "PDF Version",
	"Page" : "Page",
	"PageGeometryBoxes" : "Page geometry boxes",
	"PageGeometrySafety" : "Page geometry boxes & safety zone",
	"PageInformation" : "Page information",
	"PageRotation" : "Page rotation",
	"PageScalingFactor" : "Page scaling factor",
	"PagesVary" : "Page sizes vary in document",
	"Path" : "Path",
	"PerDocument" : "Per document",
	"PerPage" : "Per page",
	"PreflightReport" : "Preflight Report",
	"ProcessPages" : "Processed pages",
	"ProcessSeparation" : "Process separation",
	"ProcessedBy" : "Processed by",
	"ProcessedByOn" : "on",
	"Producer" : "Producer",
	"Profile" : "Profile",
	"ReportGeneratedBy" : "Report generated by",
	"Result" : "Result",
	"RuleMoreMatchesOnOnePage" : 
	{
		"MATCH_COUNT" : "",
		"PAGE_COUNT" : "",
		"RULE_NAME" : "",
		"msg" : "@(RULE_NAME) (@(MATCH_COUNT) matches on @(PAGE_COUNT) page)"
	},
	"RuleMoreMatcheshOnMorePages" : 
	{
		"MATCH_COUNT" : "",
		"PAGE_COUNT" : "",
		"RULE_NAME" : "",
		"msg" : "@(RULE_NAME) (@(MATCH_COUNT) matches on @(PAGE_COUNT) pages)"
	},
	"RuleOneMatchOnMorePages" : 
	{
		"MATCH_COUNT" : "",
		"PAGE_COUNT" : "",
		"RULE_NAME" : "",
		"msg" : "@(RULE_NAME) (@(MATCH_COUNT) match on @(PAGE_COUNT) pages)"
	},
	"RuleOneMatchOnOnePage" : 
	{
		"MATCH_COUNT" : "",
		"PAGE_COUNT" : "",
		"RULE_NAME" : "",
		"msg" : "@(RULE_NAME) (@(MATCH_COUNT) match on @(PAGE_COUNT) page)"
	},
	"SafetyDistanceInside" : "Safety distance inside",
	"SafetyDistanceOutside" : "Safety distance outside",
	"SafetyZone" : "Safety zone",
	"SeparationPreview" : "Separation preview",
	"SpotColorInformation" : "Spot color information",
	"SpotName" : "Name",
	"SpotSeparation" : "Spot color separation",
	"Standards" : "Standards",
	"SummaryReportFor" : "Summary report for",
	"Threshold" : "Threshold (%)",
	"Title" : "Title",
	"Total" : "Total",
	"TotalResults" : "Total results",
	"Trapping" : "Trapping",
	"UsedOnPage" : "Used on page",
	"UsedOnPages" : "Used on pages",
	"Warnings" : "Warnings"
}
;
var cals_env_info =  
{
	"date" : "2022-09-05T17:50:06+02:00",
	"language" : "en",
	"machine_name" : "Max Mac mini",
	"os_version_major" : 10,
	"os_version_minor" : 15,
	"os_version_text" : "macOS 10.15.7",
	"tool_name" : "callas pdfToolbox",
	"tool_variant" : "Desktop",
	"tool_version" : "14.0 (596 INTERNAL BUILD 2022-08-29 00:42:33)",
	"tool_version_build" : 596,
	"tool_version_major" : 14,
	"tool_version_minor" : 0,
	"user_name" : "Max Mustermann"
}
;
var cals_doc_info =  
{
	"docs" : 
	[
		{
			"docinfo" : 
			{
				"CreationDate" : "D:20170830083909+02'00'",
				"Creator" : "Adobe InDesign CC 2017 (Macintosh)",
				"ModDate" : "D:20220826160318+02'00'",
				"Producer" : "Adobe PDF Library 15.0",
				"Title" : "",
				"Trapped" : "False"
			},
			"file_name" : "Anzeige_callas_v5_final_neu 2_7C.pdf",
			"file_path" : "/Users/max/Downloads",
			"file_size" : "6226703",
			"nplates" : 7,
			"num_pages" : 1,
			"pages" : 
			[
				{
					"page" : 1,
					"page_img" : "img/cals_pages/20/1/cals_src_a.png",
					"page_label" : "1"
				}
			],
			"pdf_version" : "1.4",
			"plates" : [ "Black", "Cyan", "Green", "Magenta", "Orange", "Violet", "Yellow" ],
			"standards" : []
		}
	]
}
;
var cals_res_info =  
{
	"errors" : "9",
	"infos" : "0",
	"processed_pages" : 1,
	"profile_name" : "Test Profil",
	"profile_type" : "profile",
	"steps" : 
	[
		{
			"errors" : "9",
			"fixups" : [],
			"hits" : 
			[
				{
					"custom_id" : "",
					"matches" : 9,
					"on_pages" : [ 0 ],
					"pages" : 1,
					"rule_name" : "Test Check in Profile",
					"severity" : "error"
				}
			],
			"infos" : "0",
			"name" : "Test Profil",
			"type" : "profile",
			"warnings" : "0"
		}
	],
	"vars" : {},
	"warnings" : "0"
}
;
var cals_sec_info =  
{
	"preview" : 
	{
		"on_pages" : [ 1 ],
		"pageselector" : "1",
		"resolution" : 20.0
	}
}
;
